#!/usr/bin/env ruby
# frozen_string_literal: true

# Script to auto-generate a voting session from a list of external URLs
# Usage: ruby create_external_session.rb <session-name> <urls-file>

require 'fileutils'
require 'tty-prompt'
require 'pastel'

def create_external_session(session_name, urls_file, prompt, pastel)
  # Expand path
  urls_file = File.expand_path(urls_file)

  # Validate inputs
  unless File.exist?(urls_file)
    puts pastel.red("Error: URLs file '#{urls_file}' does not exist")
    return
  end

  # Read URLs
  print pastel.cyan("Reading URLs... ")
  urls = File.readlines(urls_file).map(&:strip).reject(&:empty?)

  if urls.empty?
    puts pastel.red("\nError: No URLs found in '#{urls_file}'")
    return
  end
  puts pastel.green("Found #{urls.length} URLs")

  # Create session folder
  session_path = File.join('critiq', session_name)
  
  if Dir.exist?(session_path)
    unless prompt.yes?("Session '#{session_name}' already exists. Overwrite?")
      puts pastel.yellow("Cancelled.")
      return
    end
  end

  FileUtils.mkdir_p(session_path)

  # Generate index.html content
  html_content = <<~HTML
    ---
    layout: critiq_layout
    title: "#{session_name.split('_').map(&:capitalize).join(' ')}"
    session_id: #{session_name}
    images:
    #{urls.map { |u| "  - #{u}" }.join("\n")}
    ---

    <!-- Voting interface will be automatically generated by the layout -->
  HTML

  # Write index.html
  File.write(File.join(session_path, 'index.html'), html_content)

  puts ""
  puts pastel.green("✅ Created external voting session: #{session_name}")
  puts pastel.dim("📁 Location: #{session_path}")
  puts pastel.dim("🖼️  Photos: #{urls.length}")
  puts pastel.bold("🔗 URL: http://127.0.0.1:4000/critiq/#{session_name}/")
  puts ""
  puts pastel.yellow("Next steps:")
  puts "1. Review the generated page at the URL above"
  puts "2. Share the URL with voters"
  puts "3. View results at: http://127.0.0.1:4000/critiq/admin.html"
end

# Main execution
prompt = TTY::Prompt.new
pastel = Pastel.new

if ARGV.length == 2
  session_name = ARGV[0]
  urls_file = ARGV[1]
  
  # Validate session name
  unless session_name.match?(/^[a-z0-9_]+$/)
    puts pastel.red("Error: Session name should only contain lowercase letters, numbers, and underscores")
    exit 1
  end
else
  puts pastel.bold("Create a new External Critiq Session")
  
  session_name = prompt.ask("Session name (lowercase, numbers, underscores):") do |q|
    q.required true
    q.validate /^[a-z0-9_]+$/
    q.messages[:valid?] = "Invalid format. Use lowercase letters, numbers, and underscores only."
  end

  urls_file = prompt.ask("Path to URLs file (text file with one URL per line):") do |q|
    q.required true
    q.validate ->(path) { File.exist?(File.expand_path(path)) }
    q.messages[:valid?] = "File does not exist."
  end
end

create_external_session(session_name, urls_file, prompt, pastel)
