#!/usr/bin/env ruby
# frozen_string_literal: true

# Script to auto-generate a voting session from a folder of photos
# Usage: ruby create_critiq_session.rb <session-name> <photos-folder>

require 'fileutils'

def create_voting_session(session_name, photos_folder)
  # Validate inputs
  unless Dir.exist?(photos_folder)
    puts "Error: Photos folder '#{photos_folder}' does not exist"
    exit 1
  end

  # Find all image files
  image_extensions = %w[.jpg .jpeg .png .gif .webp .JPG .JPEG .PNG .GIF .WEBP]
  photos = Dir.glob("#{photos_folder}/*").select do |file|
    File.file?(file) && image_extensions.include?(File.extname(file))
  end

  if photos.empty?
    puts "Error: No photos found in '#{photos_folder}'"
    exit 1
  end

  # Sort photos by filename
  photos.sort!

  # Create session folder
  session_path = File.join('critiq', session_name)
  FileUtils.mkdir_p(session_path)

  # Copy photos to session folder
  photos.each do |photo|
    FileUtils.cp(photo, session_path)
  end

  # Get just the filenames for the YAML
  photo_filenames = photos.map { |p| File.basename(p) }

  # Generate index.html content
  html_content = <<~HTML
    ---
    layout: critiq_layout
    title: "#{session_name.split('_').map(&:capitalize).join(' ')}"
    session_id: #{session_name}
    images:
    #{photo_filenames.map { |f| "  - #{f}" }.join("\n")}
    ---

    <!-- Voting interface will be automatically generated by the layout -->
  HTML

  # Write index.html
  File.write(File.join(session_path, 'index.html'), html_content)

  puts "✅ Created voting session: #{session_name}"
  puts "📁 Location: #{session_path}"
  puts "🖼️  Photos: #{photos.length}"
  puts "🔗 URL: http://127.0.0.1:4000/critiq/#{session_name}/"
  puts ""
  puts "Next steps:"
  puts "1. Review the generated page at the URL above"
  puts "2. Share the URL with voters (it won't appear in navigation)"
  puts "3. View results at: http://127.0.0.1:4000/critiq/admin.html"
end

# Main execution
if ARGV.length != 2
  puts "Usage: ruby create_critiq_session.rb <session-name> <photos-folder>"
  puts ""
  puts "Example:"
  puts "  ruby create_critiq_session.rb paris_2025 ~/Desktop/paris_photos"
  puts ""
  puts "Session name should:"
  puts "  - Use lowercase letters, numbers, and underscores only"
  puts "  - Be URL-friendly (no spaces or special characters)"
  exit 1
end

session_name = ARGV[0]
photos_folder = ARGV[1]

# Validate session name
unless session_name.match?(/^[a-z0-9_]+$/)
  puts "Error: Session name should only contain lowercase letters, numbers, and underscores"
  exit 1
end

create_voting_session(session_name, photos_folder)
