#!/usr/bin/env ruby
# frozen_string_literal: true

# Script to auto-generate a voting session from a list of external URLs
# Usage: ruby create_external_session.rb <session-name> <urls-file>

require 'fileutils'

def create_external_session(session_name, urls_file)
  # Validate inputs
  unless File.exist?(urls_file)
    puts "Error: URLs file '#{urls_file}' does not exist"
    exit 1
  end

  # Read URLs
  urls = File.readlines(urls_file).map(&:strip).reject(&:empty?)

  if urls.empty?
    puts "Error: No URLs found in '#{urls_file}'"
    exit 1
  end

  # Create session folder
  session_path = File.join('critiq', session_name)
  FileUtils.mkdir_p(session_path)

  # Generate index.html content
  html_content = <<~HTML
    ---
    layout: critiq_layout
    title: "#{session_name.split('_').map(&:capitalize).join(' ')}"
    session_id: #{session_name}
    images:
    #{urls.map { |u| "  - #{u}" }.join("\n")}
    ---

    <!-- Voting interface will be automatically generated by the layout -->
  HTML

  # Write index.html
  File.write(File.join(session_path, 'index.html'), html_content)

  puts "✅ Created external voting session: #{session_name}"
  puts "📁 Location: #{session_path}"
  puts "🖼️  Photos: #{urls.length}"
  puts "🔗 URL: http://127.0.0.1:4000/critiq/#{session_name}/"
  puts ""
  puts "Next steps:"
  puts "1. Review the generated page at the URL above"
  puts "2. Share the URL with voters"
  puts "3. View results at: http://127.0.0.1:4000/critiq/admin.html"
end

# Main execution
if ARGV.length != 2
  puts "Usage: ruby create_external_session.rb <session-name> <urls-file>"
  puts ""
  puts "Example:"
  puts "  ruby create_external_session.rb paris_2025 urls.txt"
  puts ""
  puts "Session name should:"
  puts "  - Use lowercase letters, numbers, and underscores only"
  exit 1
end

session_name = ARGV[0]
urls_file = ARGV[1]

# Validate session name
unless session_name.match?(/^[a-z0-9_]+$/)
  puts "Error: Session name should only contain lowercase letters, numbers, and underscores"
  exit 1
end

create_external_session(session_name, urls_file)
