#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Generates, for every photo under uploads/ images/ projects/:
#   1. a sibling .webp (originals are never modified)
#   2. an entry in _data/image_sizes.yml so templates can emit width/height
#      and browsers stop reflowing galleries as they load.
#
# Idempotent: skips a .webp that is newer than its source. Run after adding
# photos, then commit both the source and the .webp.
#
#   ruby tools/build_images.rb
#
# Requires: cwebp, identify (brew install webp imagemagick)

require 'yaml'
require 'shellwords'

ROOT = File.expand_path('..', __dir__)
DIRS = %w[uploads images projects critiq].freeze
QUALITY = 82

Dir.chdir(ROOT)

%w[cwebp identify].each do |bin|
  abort "#{bin} not found. brew install webp imagemagick" if `which #{bin}`.strip.empty?
end

sources = DIRS.flat_map { |d| Dir.glob("#{d}/**/*.{jpg,jpeg,JPG,png,PNG}") }.sort
abort 'no images found' if sources.empty?

sizes = {}
built = 0
skipped = 0

sources.each do |src|
  webp = "#{src.sub(/\.[^.]+\z/, '')}.webp"

  if File.exist?(webp) && File.mtime(webp) >= File.mtime(src)
    skipped += 1
  else
    ok = system("cwebp -quiet -q #{QUALITY} -metadata none #{Shellwords.escape(src)} -o #{Shellwords.escape(webp)}")
    unless ok
      warn "  ! cwebp failed on #{src}"
      next
    end
    built += 1
  end

  dims = `identify -format '%w %h' #{Shellwords.escape(src)}[0] 2>/dev/null`.split
  next unless dims.size == 2

  # Keys are site-absolute so templates can look up by the same string they render.
  sizes["/#{src}"] = { 'w' => dims[0].to_i, 'h' => dims[1].to_i }
end

Dir.mkdir('_data') unless Dir.exist?('_data')
File.write('_data/image_sizes.yml',
           "# Generated by tools/build_images.rb. Do not edit by hand.\n" + sizes.to_yaml)

src_bytes = sources.sum { |f| File.size(f) }
webp_bytes = sources.sum do |f|
  w = "#{f.sub(/\.[^.]+\z/, '')}.webp"
  File.exist?(w) ? File.size(w) : 0
end

puts format('built %d, skipped %d, indexed %d', built, skipped, sizes.size)
puts format('source %.1f MB -> webp %.1f MB (%.0f%% smaller)',
            src_bytes / 1e6, webp_bytes / 1e6,
            100 - (webp_bytes.to_f / src_bytes * 100))
